# basic options
title: Personal Website of Uttam Paudel
author: Uttam Paudel
email: upp5020@psu.edu
description: A repository.
twitter_username: @Mr.Paudell
github_username:  uttampa

# Build settings
markdown: kramdown
theme: minima
