# basic options
title: Home
author: Uttam Paudel
email: upp5020@psu.edu
description: Welcome to America. 
twitter_username: Mr.Paudell
github_username:  uttampa

# Build settings
markdown: kramdown
theme: minima
